[project]
name = "portfolio-generator"
version = "0.1.0"
description = "Manage portfolio website"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jinja2==3.1.4",
    "markupsafe==3.0.2",
]
